#!/bin/sh
version=4.5.7
project=echeck.
git clean -d -f -x
tar c --exclude-vcs-ignores \
	--exclude-vcs \
	--exclude=debian \
	-Jvf ../$project_$version.orig.tar.xz --xform='s/./$project-$version/' .
dpkg-buildpackage -rfakeroot -D -us -uc

